---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hamish.
--- DateTime: 2022/2/5 14:27
---
local function scan(key)
    local cursor = 0
    local keynum = 0
    local r={}
    repeat
        local res = redis.call("scan", cursor, "match", key,'COUNT',100)

        if (res ~= nil and #res >= 0) then
            redis.replicate_commands()
            cursor = tonumber(res[1])
            local ks = res[2]
            keynum = #ks
            for i=1,keynum,1 do
                local k = tostring(ks[i])
                table.insert(r, k)
            end
        end
    until (cursor <= 0)

    return r
end

local userLocks=scan(KEYS[1]);

return userLocks;